### ISSUE TITLE
Out of bound access in fenwick_inc

### ISSUE THREAD

**Issue by BenKaufmann** [ahtotruu/fenwick#1]
Hi,

I think the function fenwick_inc has a possible out of bound access.
Consider an array a of size n = 10, and a call fenwick_inc(a, n, 7, 1):
The condition `if ((i & m) == 0)` will be true for m = 8 < n, leading to a write at a[15].

One possible fix could be to change the loop condition from `m < n` to `(m + i) < n`.

Regards,
Ben

**Comment by ahtotruu** [comment]
Thanks for reporting this. Should be corrected now.

And sorry it took so long. For some reason I did not get any notification about an issue being opened.
